# Generated by Django 4.1 on 2024-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
    ]
