# Generated by Django 4.1 on 2024-06-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
        ('opportunities', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='stage',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='stages.stage'),
        ),
    ]
