# Generated by Django 4.1 on 2024-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_remove_opportunity_stage_opportunity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='status',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('QUALIFICATION', 'QUALIFICATION'), ('NEEDS ANALYSIS', 'NEEDS ANALYSIS'), ('VALUE PROPOSITION', 'VALUE PROPOSITION'), ('ID.DECISION MAKERS', 'ID.DECISION MAKERS'), ('PERCEPTION ANALYSIS', 'PERCEPTION ANALYSIS'), ('PROPOSAL/PRICE QUOTE', 'PROPOSAL/PRICE QUOTE'), ('NEGOTIATION/REVIEW', 'NEGOTIATION/REVIEW'), ('CLOSED WON', 'CLOSED WON'), ('CLOSED LOST', 'CLOSED LOST')], default='NEEDS ANALYSIS', max_length=64),
        ),
    ]
